const navToggle=document.querySelector('.nav-toggle');
const nav=document.getElementById('site-nav');
navToggle.addEventListener('click',()=>{const open=navToggle.getAttribute('aria-expanded')==='true';navToggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');navToggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));
function setupFilter(buttonSelector,cardSelector,statusId){const buttons=[...document.querySelectorAll(buttonSelector)];const cards=[...document.querySelectorAll(cardSelector)];buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(item=>item.setAttribute('aria-pressed',String(item===button)));const filter=button.dataset.projectFilter||button.dataset.credentialFilter;let count=0;cards.forEach(card=>{const categories=(card.dataset.projectCategory||card.dataset.credentialCategory).split(' ');card.hidden=filter!=='all'&&!categories.includes(filter);if(!card.hidden)count+=1});document.getElementById(statusId).textContent=`${count} ${count===1?'item':'items'} shown.`}))}
setupFilter('[data-project-filter]','[data-project-category]','project-status');setupFilter('[data-credential-filter]','[data-credential-category]','credential-status');
const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('#site-nav a').forEach(link=>{if(link.hash===`#${entry.target.id}`)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')})}})},{rootMargin:'-25% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(section=>sectionObserver.observe(section));
document.getElementById('copy-email').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText('manas150309@gmail.com');status.textContent='Email copied to clipboard.'}catch{status.textContent='Email: manas150309@gmail.com'}});
